language: java

matrix:
  include:
    - os: linux
      jdk: openjdk8
      addons:
        apt:
          packages:
            - openjfx
            - rpm
            - fakeroot
    - os: osx
      osx_image: xcode9.3

script:
  - ./gradlew jfxNative
  - ls -l build/jfx/native

deploy:
  provider: releases
  api_key:
    secure: GJTCNQiJZ5HcZFl+K/yr2rPZfx6Y+UtLBW5n1WhduqLM+rRoM8Cn4UoVYv8gKHx0r0m+Jb8j2oBRvuSzLrO0aqfi2UuhfmmB6+bvbD4kvN1lHrgzKuXROrGtm5Zhj+D6edZ42E2LCCKyBYmEqhYJpWt9ZMp12eBO0oIZf4fdQnbbRB8ndtawLRMmACeXZW3taAwzOKlGLIKErOYcWwp9cab9jRkNtyyfIrXQJ16ZeVm0x2vSLqXZvDMqCuOUjNy+gDPp/vvonP38A69hk84WJaolNhHIA3WvzjmzDYLo4dxx8aLixsMP8A0XNm8830lhRLiPdWTOs8eV1hXiSLoZAApDJy7v74v3FKbGBA6wiYz6pwCcEIivyqf0liwPEssqmDAfHb+a+ellk2gkJgyJPIJR5KqeH6CboAOhIJlKJs4YFHRdNmV7lCUvHkhGQwWgXpXQ0u/9WICiMeZSZqlq7eEEeyzLFIdNcOdFEYKVtspLfeBr4fnuINVjKjECmJ8bUZBlkNznKhRYfcQUcV6y7SeNS2CpQXUedsp5UMQ6n/jTdCaRRLkRplANIxEORdbGmHueO9mGAmcrZsIEPoSyWXw+PXADv0nq8f2ik7UFEqlTd7hKbw2tJCvYR1yRE+PhCQ2VX912fw5frJ2kKwky/E/5vpTCSCkzTwWxlvbQ8wg=
  file_glob: true
  file:
    - 'build/jfx/native/*.deb'
    - 'build/jfx/native/*.rpm'
    - 'build/jfx/native/*.pkg'
  skip_cleanup: true
  on:
    tags: true
